### PR TITLE
Log config repo was updated

### PR DESCRIPTION
**Pull request by olivergondza**
@pjanouse

### CODE REVIEW

**Comment by olivergondza** [comment]
Good point

**Comment by olivergondza** [comment]
Addressed

**Comment by pjanouse** [comment]
Note: It doesn't work correctly, there are many messages in log like:

INFO: Config repo for NodeSharing-0a944b2f updated from AnyObjectId[aa3ed278e369a557dbdd7c3ce09dbb9f158097ad] to AnyObjectId[aa3ed278e369a557dbdd7c3ce09dbb9f158097ad]

but there isn't any update on Git repo hosting side.

**Comment by pjanouse** [comment]
Seems working not, however the LOG msg is not much informational:

> INFO: Config repo updated from a9f34e65509e37212ef4d2ef784d348bdb479c3a to 17cee61d9924d7e295ca5bc81a84b57df8a4a509

**Comment by olivergondza** [comment]
As agreed, those sha1 commit hashes are good for now - can be improved in the future.

**Pull request merged**
